-- -- ChangeSet: 1 - Create Questionnaire Table
-- CREATE TABLE questionnaire (
--                                id SERIAL PRIMARY KEY,
--                                title VARCHAR(255) NOT NULL,
--                                description TEXT,
--                                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--                                updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
-- );
--
-- -- ChangeSet: 2 - Insert Sample Data
-- INSERT INTO questionnaire (id, title, description, created_at, updated_at) VALUES
--                                                                                (1, 'Customer Satisfaction Survey', 'A survey to assess customer satisfaction with our services.', '2024-01-01 12:00:00', '2024-01-01 12:00:00'),
--                                                                                (2, 'Product Feedback Form', 'A form to gather feedback on our new product.', '2024-01-01 12:00:00', '2024-01-01 12:00:00');


DROP TABLE IF EXISTS nutrition_goals;

CREATE TABLE nutrition_goals (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
    goal int2 NULL,
    questionnaire_id int8 NOT NULL,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NULL,
    CONSTRAINT nutrition_goals_goal_check CHECK (((goal >= 0) AND (goal <= 4))),
    CONSTRAINT nutrition_goals_pkey PRIMARY KEY (id)
);